//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sduo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        public Course()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Kode")]
        [Required]
        public string Code { get; set; }
        [Display(Name = "Beskrivelse")]
        [Required]
        public string Description { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
